// ============================================================================
// File Output Module
// ============================================================================
// Writes player data to seed files

import * as fs from 'fs/promises';
import * as path from 'path';
import type { FictionalPlayer } from '../ai/transform.js';
import { generateTypeScript } from './typescript.js';

const PLAYERS_DIR = path.resolve(
  process.cwd(),
  '../../packages/core/src/data/players',
);

/**
 * Append a player to the appropriate team file
 */
export async function appendToPlayerFile(
  player: FictionalPlayer,
): Promise<void> {
  const filePath = path.join(PLAYERS_DIR, `${player.teamId}.ts`);

  // Ensure directory exists
  await fs.mkdir(PLAYERS_DIR, { recursive: true });

  // Check if file exists
  let fileExists = false;
  try {
    await fs.access(filePath);
    fileExists = true;
  } catch {
    fileExists = false;
  }

  if (fileExists) {
    // Append to existing file
    await appendToExistingFile(filePath, player);
  } else {
    // Create new file
    await createNewPlayerFile(filePath, player);
  }
}

/**
 * Append player to existing file
 */
async function appendToExistingFile(
  filePath: string,
  player: FictionalPlayer,
): Promise<void> {
  const content = await fs.readFile(filePath, 'utf-8');
  const playerCode = generateTypeScript(player);

  // Find the closing bracket of the array
  const lastBracketIndex = content.lastIndexOf('];');

  if (lastBracketIndex === -1) {
    throw new Error(`Could not find array end in ${filePath}`);
  }

  // Check if there are existing players (look for closing brace before the bracket)
  const beforeBracket = content.slice(0, lastBracketIndex).trim();
  const needsComma = beforeBracket.endsWith('}') || beforeBracket.endsWith(',');

  // Insert the new player
  const newContent =
    content.slice(0, lastBracketIndex) +
    (needsComma ? '' : '') +
    `  ${playerCode.split('\n').join('\n  ')},\n` +
    content.slice(lastBracketIndex);

  await fs.writeFile(filePath, newContent, 'utf-8');
}

/**
 * Create a new player file for a team
 */
async function createNewPlayerFile(
  filePath: string,
  player: FictionalPlayer,
): Promise<void> {
  const teamName = getTeamName(player.teamId);
  const playerCode = generateTypeScript(player);

  const content = `// ============================================================================
// RETROFOOT - ${teamName} Players
// ============================================================================
// Generated by player-lookup tool

import type { Player } from '@retrofoot/core/types';
import { createDefaultForm } from '@retrofoot/core/types';

/**
 * Player seed data for ${teamName}
 * These are templates copied to the database when starting a new game
 */
export const ${player.teamId.toUpperCase()}_PLAYERS: Omit<Player, 'id'>[] = [
  ${playerCode.split('\n').join('\n  ')},
];
`;

  await fs.writeFile(filePath, content, 'utf-8');
}

/**
 * Get team name from ID
 */
function getTeamName(teamId: string): string {
  const names: Record<string, string> = {
    mengalvio: 'Mengalvio FC',
    palestra: 'SE Palestra',
    timao: 'Timão Paulista',
    trikas: 'Trikas FC',
    acmineiro: 'AC Mineiro',
    putfire: 'Putfire',
    flordelince: 'Flor de Lince',
    colorado: 'CR Colorado',
    gpa: 'Grupo Porto-Alegrense',
    cabuloso: 'Cabuloso Estrelado',
    tdcolina: 'Time da Colina CR',
    baleia: 'CR Baleia',
    esquadrao: 'Esquadrão DA',
    paranaense: 'Paranaense',
    massabruta: 'Massa Bruta SC',
    leaodabarra: 'Leão da Barra',
    coxaverde: 'Coxa-Verde EC',
    chapaquente: 'SC Chapa Quente',
    leaoazul: 'Leão Azul',
    laranjamecanica: 'AS Laranja Mecânica',
  };

  return names[teamId] || teamId;
}
