// ============================================================================
// TypeScript Output Generator
// ============================================================================
// Generates TypeScript code for player objects

import type { FictionalPlayer } from '../ai/transform.js';

/**
 * Generate TypeScript code for a player object
 */
export function generateTypeScript(player: FictionalPlayer): string {
  const { attributes } = player;

  return `{
  templateId: '${player.templateId}',
  name: '${escapeString(player.name)}',
  ${player.nickname ? `nickname: '${escapeString(player.nickname)}',` : '// No nickname'}
  realInspiration: '${escapeString(player.realInspiration)}',
  teamId: '${player.teamId}',
  position: '${player.position}',
  age: ${player.age},
  nationality: '${escapeString(player.nationality)}',
  preferredFoot: '${player.preferredFoot}',
  attributes: {
    speed: ${attributes.speed},
    strength: ${attributes.strength},
    stamina: ${attributes.stamina},
    shooting: ${attributes.shooting},
    passing: ${attributes.passing},
    dribbling: ${attributes.dribbling},
    heading: ${attributes.heading},
    tackling: ${attributes.tackling},
    positioning: ${attributes.positioning},
    vision: ${attributes.vision},
    composure: ${attributes.composure},
    aggression: ${attributes.aggression},
    reflexes: ${attributes.reflexes},
    handling: ${attributes.handling},
    diving: ${attributes.diving},
  },
  potential: ${player.potential},
  status: 'active',
  contractEndSeason: ${player.contractEndSeason},
  wage: ${player.wage},
  marketValue: ${player.marketValue},
  form: {
    form: 70,
    lastFiveRatings: [],
    seasonGoals: 0,
    seasonAssists: 0,
    seasonMinutes: 0,
    seasonAvgRating: 0,
  },
}`;
}

/**
 * Generate a full player file for a team
 */
export function generatePlayerFile(
  teamId: string,
  teamName: string,
  players: FictionalPlayer[],
): string {
  const playerCode = players.map((p) => generateTypeScript(p)).join(',\n');

  return `// ============================================================================
// RETROFOOT - ${teamName} Players
// ============================================================================
// Generated by player-lookup tool

import type { PlayerSeed } from '../types.js';

export const ${teamId.toUpperCase()}_PLAYERS: PlayerSeed[] = [
${playerCode}
];
`;
}

/**
 * Escape special characters in strings
 */
function escapeString(str: string): string {
  return str.replace(/'/g, "\\'").replace(/\n/g, '\\n');
}
