// ============================================================================
// RETROFOOT - Mengalvio FC Players
// ============================================================================
// Generated by player-lookup tool

import type { Player } from '../../types';

/**
 * Seed data extends Player with template metadata
 */
export interface PlayerSeed
  extends Omit<
    Player,
    'id' | 'morale' | 'fitness' | 'injured' | 'injuryWeeks'
  > {
  templateId: string;
  realInspiration: string;
  teamId: string;
}

/**
 * Player seed data for Mengalvio FC
 * These are templates copied to the database when starting a new game
 */
export const MENGALVIO_PLAYERS: PlayerSeed[] = [
  {
    templateId: 'paulo-guilherme-abrantes-dos-sabados',
    name: 'Paulo Guilherme Abrantes dos Sabados',
    nickname: 'Paulito',
    realInspiration: 'Pedro Guilherme Abreu dos Santos',
    teamId: 'mengalvio',
    position: 'ATT',
    age: 27,
    nationality: 'Brazil',
    preferredFoot: 'right',
    attributes: {
      speed: 87,
      strength: 78,
      stamina: 77,
      shooting: 98,
      passing: 75,
      dribbling: 90,
      heading: 79,
      tackling: 59,
      positioning: 90,
      vision: 80,
      composure: 93,
      aggression: 80,
      reflexes: 47,
      handling: 37,
      diving: 46,
    },
    potential: 82,
    status: 'active',
    contractEndSeason: 2027,
    wage: 44100,
    marketValue: 18000000,
    form: {
      form: 70,
      lastFiveRatings: [],
      seasonGoals: 0,
      seasonAssists: 0,
      seasonMinutes: 0,
      seasonAvgRating: 0,
    },
  },
];
